device: cuda:1  # can infer using only 1 gpu
verbose: True  # whether print statistics or not

checkpoints: "/root/lgsc/logs/baseline/tensorboard/default/version_8/checkpoints/epoch=49.ckpt"  # path to pl checkpoint

image_size: 224  # size of input image
mean:
  r: 0
  g: 0
  b: 0
std:
  r: 1
  g: 1
  b: 1

#mean: # use Imagenet values
#  r: 0.485
#  g: 0.456
#  b: 0.406
#std:
#  r: 0.229
#  g: 0.224
#  b: 0.225

with_labels: True  # Whether your csv file has labels or not
num_workers: 0  # param for infer dataloader
batch_size: 12  # batch size for infer dataloader

# uncomment this, to use online face cropping
# however it is not recommended
# you can only use cpu device as device for face-cropping nn
#face_detector:
#  image_size: 512
#  margin: 100
#  min_face_size: 100
#  thresholds: [0.6, 0.7, 0.7]
#  factor: 0.709
#  device: *device
#
#infer_df: "/root/datasets/HKBU-V2/test.csv"  # path to csv file with test data
#root: "/root/datasets/HKBU-V2"  # prefix path to your images
#out_file:  "/root/lgsc/results/version_1_hkbu.txt"  # path to file you want save your results

#infer_df: "/root/datasets/meta-fas-experiment/protocol_1/test.csv"  # path to csv file with test data
#root: "/root/datasets/HKBU-V2"  # prefix path to your images
#out_file:  "/root/lgsc/results/version_8_hkbu.txt"  # path to file you want save your results

infer_df: "/root/datasets/meta-fas-experiment/protocol_1/val.csv"  # path to csv file with test data
root: "/root/datasets/HKBU-V2"  # prefix path to your images
out_file:  "/root/lgsc/results/version_8_val.txt"  # path to file you want save your results

#infer_df: "/root/datasets/HKBU-V2/hkbu_01_no_industrial.csv"  # path to csv file with test data
#root: "/root/datasets/HKBU-V2"  # prefix path to your images
#out_file:  "/root/lgsc/results/version_8_hkbu_01_no_indust.txt"  # path to file you want save your results
